import React from 'react';
import ReactDOM from 'react-dom';
import './shared/removePolyfill';
import {
  Alert,
  Breadcrumbs,
  BulletedList,
  Button,
  ButtonGroup,
  Checkbox,
  Drawer,
  Dropdown,
  EmailInput,
  Field,
  Form,
  KeyValueInput,
  List,
  ListItem,
  Menu,
  NavListItem,
  Panel,
  PasswordInput,
  Popover,
  PrimaryNav,
  RadioButtonInput,
  SecondaryNav,
  SearchInput,
  SelectInput,
  Text,
  TextInput,
  TextListItem,
  Theme,
  VectorGraphic,
  Version,
  // colors
  ButtonColors,
  BackgroundColors,
  FormColors,
  IconColors,
  NoticeColors,
  StructuralColors,
  TextColors,
  // styles
  Resets,
} from './Sprinkles';


// export Sprinkles, React and ReactDOM globally
window.Sprinkles = {
  Alert,
  Breadcrumbs,
  BulletedList,
  Button,
  ButtonGroup,
  Checkbox,
  Drawer,
  Dropdown,
  EmailInput,
  Field,
  Form,
  KeyValueInput,
  List,
  ListItem,
  Menu,
  NavListItem,
  Panel,
  PasswordInput,
  Popover,
  PrimaryNav,
  RadioButtonInput,
  SecondaryNav,
  SearchInput,
  SelectInput,
  Text,
  TextInput,
  TextListItem,
  Theme,
  VectorGraphic,
  Version,
  // colors
  ButtonColors,
  BackgroundColors,
  FormColors,
  IconColors,
  NoticeColors,
  StructuralColors,
  TextColors,
  // Styles
  Resets,
};
window.React = React;
window.ReactDOM = ReactDOM;
