import React from "react";
import ReactDOM from "react-dom";
import {
  Alert,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Drawer,
  Dropdown,
  EmailInput,
  Field,
  Form,
  KeyValueInput,
  List,
  ListItem,
  NavListItem,
  Panel,
  PasswordInput,
  Popover,
  PrimaryNav,
  RadioButtonInput,
  SecondaryNav,
  SelectInput,
  Text,
  TextInput,
  TextListItem,
  VectorGraphic,
  Version,
  // colors
  ButtonColors,
  BackgroundColors,
  Colors,
  StructuralColors,
  TextColors,
} from "./Sprinkles";


// export Sprinkles, React and ReactDOM globally
window.Sprinkles = {
  Alert,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Drawer,
  Dropdown,
  EmailInput,
  Field,
  Form,
  KeyValueInput,
  List,
  ListItem,
  NavListItem,
  Panel,
  PasswordInput,
  Popover,
  PrimaryNav,
  RadioButtonInput,
  SecondaryNav,
  SelectInput,
  Text,
  TextInput,
  TextListItem,
  VectorGraphic,
  Version,
  // colors
  ButtonColors,
  BackgroundColors,
  Colors,
  StructuralColors,
  TextColors,
};
window.React = React;
window.ReactDOM = ReactDOM;
